name: wishes_app
publish_to: 'none' 

version: 1.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # PLUGINS
  url_strategy: 0.2.0
  url_launcher: 6.2.3
  url_launcher_web: 2.2.3
  image_picker: 1.0.4
  image_picker_for_web: 3.0.1
  share_plus: 7.2.1
  
  # USER INTERFACE
  cupertino_icons: 1.0.2
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.3+1  
  flutter_svg: 2.0.9
  

  # REPOSITORY
  firebase_core: ^2.23.0
  firebase_messaging: ^14.7.5
  firebase_analytics: ^10.7.1
  firebase_auth: ^4.14.1
  firebase_crashlytics: ^3.4.8
  uuid: 4.2.1
  http: 1.1.0
  shared_preferences: 2.2.2
  encrypt: 5.0.3

  # VIEWMODEL
  flutter_bloc: 8.1.3
  equatable: 2.0.5
  bloc: 8.1.2
  bloc_concurrency: 0.2.2
  provider: 6.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/banner/
    - assets/icons/